// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjkytcickscjfnpompmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqa3l0Y2lja3NjamZucG9tcG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2ODQ2MzksImV4cCI6MjA1MDI2MDYzOX0.4vot5Qqdq2czEAnTEGb6zh7HrfQ3TnGgYPVCXHu3C1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);